"""
Django settings for blogged project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from google.oauth2 import service_account
import dj_database_url

from common.utils import get_secret
from settings.common import * # noqa: F401


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_secret("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(os.environ.get("DEBUG", default=0))

IS_HEROKU_APP = "DYNO" in os.environ and "CI" not in os.environ

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS").split(" ")
csrf = os.environ.get("CSRF_TRUSTED_ORIGINS") # ["http://localhost:1337"]  # TODO - update for production
if csrf:
    CSRF_TRUSTED_ORIGINS = csrf.split(" ")


WSGI_APPLICATION = "blogged.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


POSTGRES_PW = get_secret("POSTGRES_PASSWORD")

if IS_HEROKU_APP:
    # In production on Heroku the database configuration is derived from the `DATABASE_URL`
    # environment variable by the dj-database-url package. `DATABASE_URL` will be set
    # automatically by Heroku when a database addon is attached to your Heroku app. See:
    # https://devcenter.heroku.com/articles/provisioning-heroku-postgres#application-config-vars
    # https://github.com/jazzband/dj-database-url
    DATABASES = {
        "default": dj_database_url.config(
            env="DATABASE_URL",
            conn_max_age=600,
            conn_health_checks=True,
            ssl_require=True,
        ),
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("DB_NAME", "eco_blog"),
            "USER": os.environ.get("DB_USER"),
            "PASSWORD": POSTGRES_PW,
            "HOST": os.environ.get("DB_HOST", "localhost"),
            "PORT": os.environ.get("DB_PORT", "5432"),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# for email contact form (followed this blog post: https://learndjango.com/tutorials/django-email-contact-form-tutorial)
# TODO - should we switch to anymail?: https://github.com/anymail/django-anymail
# need to follow the steps - "Production Email Service" to actually get the email to send
# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend" 

ANYMAIL = {
    # (exact settings here depend on your ESP...)
    "MAILGUN_API_KEY": get_secret("MAILGUN_API_KEY"),
    "MAILGUN_SENDER_DOMAIN": 'mg.jansweb.co.uk',  # your Mailgun domain, if needed
    "MAILGUN_API_URL": "https://api.eu.mailgun.net/v3",  # since we are in the EU region
}
EMAIL_BACKEND = "anymail.backends.mailgun.EmailBackend"  # comment this out to test email sending in the console instead of actually sending emails
# EMAIL_HOST = "smtp.eu.mailgun.org"  # new
# EMAIL_PORT = int(os.environ.get("EMAIL_PORT", 587))
# EMAIL_HOST_USER = os.environ.get("MAILGUN_API_KEY")
# EMAIL_HOST_PASSWORD = "<sendgrid_password>"  # new
EMAIL_USE_TLS = True  

# Google drive keys
GOOGLE_DRIVE_STORAGE_JSON_KEY_FILE = (
    "/home/jan/secrets/django-blog-data-9a52eb1b9db9.json"
)
GOOGLE_DRIVE_STORAGE_MEDIA_ROOT = (
    "blog/rewilding/images"  # <base google drive path for file uploads>' # OPTIONAL
)

# try:
#     GS_CREDENTIALS = service_account.Credentials.from_service_account_file(
#         os.environ.get("GOOGLE_APPLICATION_CREDENTIALS")
#     )
#     print("Succesfully loaded Google Cloud credentials: ")
# except Exception as e:
#     GS_CREDENTIALS = ""
#     print("Error loading Google Cloud credentials: " + str(e))
#     print("File system contents at /app: " + str(os.listdir("/app")))
#     print("File system contents at /: " + str(os.listdir("/")))

# STORAGES = {
#     "default": {
#         "BACKEND": "storages.backends.gcloud.GoogleCloudStorage",
#         "OPTIONS": {
#             "GS_BUCKET_NAME": os.environ.get("GS_BUCKET_NAME"),
#             "GS_PROJECT_ID": os.environ.get("GS_PROJECT_ID"),
#             "GS_CREDENTIALS": GS_CREDENTIALS,
#         },
#     },
#     "staticfiles": {
#         "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
#     }
# }

DEFAULT_FILE_STORAGE = "storages.backends.gcloud.GoogleCloudStorage"
IMAGEKIT_DEFAULT_FILE_STORAGE = "storages.backends.gcloud.GoogleCloudStorage"
GS_BUCKET_NAME = os.environ.get("GS_BUCKET_NAME")
GS_PROJECT_ID = os.environ.get("GS_PROJECT_ID")
try:
    GS_CREDENTIALS = service_account.Credentials.from_service_account_file(
        os.environ.get("GOOGLE_APPLICATION_CREDENTIALS")
    )
except Exception as e:
    GS_CREDENTIALS = None
    print("Error loading Google Cloud credentials: " + str(e))

MEDIA_URL = f"https://storage.googleapis.com/{GS_BUCKET_NAME}/"

# Don't store the original (un-hashed filename) version of static files, to reduce slug size:
# https://whitenoise.readthedocs.io/en/latest/django.html#WHITENOISE_KEEP_ONLY_HASHED_FILES
# WHITENOISE_KEEP_ONLY_HASHED_FILES = True

# TODO - add https://whitenoise.readthedocs.io/en/stable/index.html for whitenoise 
# google cloud - https://django-storages.readthedocs.io/en/latest/backends/gcloud.html


# For public access to images, set this to publicRead.
# GS_DEFAULT_ACL = 'publicRead' # Optional, but recommended for public images. Requires ACLs to be enabled on the bucket.
# For private images, you might want to use signed URLs.
GS_QUERYSTRING_AUTH = False  # Recommended for private images and when using signed URLs


LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"


# Check required envs exist
required_envs = ["PROJECT_DB_TAG"]

for env in required_envs:
    if not os.environ.get(env):
        raise ValueError(f"Missing required env variable: {env}")
