# Generated by Django 5.2.8 on 2026-01-09 12:02
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UrlHit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("hits", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="HitCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.CharField(max_length=40)),
                ("session", models.CharField(max_length=40)),
                ("date", models.DateTimeField(auto_now=True)),
                (
                    "url_hit",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hitcount.urlhit",
                    ),
                ),
            ],
        ),
    ]
