# Generated by Django 5.2.4 on 2025-11-23 09:39

import blog.models
import django.db.models.deletion
import django.utils.timezone
import storages.backends.gcloud
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("blog", "0001_initial"),
        ("blog", "0002_alter_post_options_comment"),
        ("blog", "0003_mediaattachment"),
        ("blog", "0004_remove_mediaattachment_image_name_and_more"),
        ("blog", "0005_googlebucketattachment"),
        ("blog", "0006_alter_googlebucketattachment_image_and_more"),
        ("blog", "0007_alter_post_slug"),
        ("blog", "0008_images"),
        ("blog", "0009_post_date"),
        ("blog", "0010_gpscoordinates"),
        ("blog", "0011_alter_images_caption"),
    ]

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("date", models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="blog.post",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GoogleBucketAttachment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "image",
                    models.ImageField(
                        storage=storages.backends.gcloud.GoogleCloudStorage(),
                        upload_to="rewilding/images",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MediaAttachment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "image",
                    models.ImageField(
                        storage=storages.backends.gcloud.GoogleCloudStorage(),
                        upload_to="rewilding/images",
                    ),
                ),
                ("caption", models.TextField(default="No caption")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "name",
                    models.CharField(default=django.utils.timezone.now, max_length=255),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="GpsCoordinates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("altitude", models.FloatField()),
                (
                    "post",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.post",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Images",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        storage=storages.backends.gcloud.GoogleCloudStorage(),
                        upload_to=blog.models.get_image_filename,
                        verbose_name="Image",
                    ),
                ),
                ("caption", models.TextField(blank=True, null=True)),
                (
                    "post",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.post",
                    ),
                ),
            ],
        ),
    ]
