# Generated by Django 5.2.8 on 2026-01-20 14:34
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="activities_tag",
        ),
        migrations.DeleteModel(
            name="Activity",
        ),
    ]
