# Generated by Django 5.2.8 on 2026-01-22 08:09
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_remove_post_activities_tag_delete_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("DR", "Draft"), ("PU", "Published"), ("AR", "Archived")],
                default="DR",
                max_length=2,
            ),
        ),
    ]
