# Generated by Django 5.2.4 on 2025-07-22 07:54

import gdstorage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAttachment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_name', models.CharField(max_length=200)),
                ('image', models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='uploaded-images')),
            ],
        ),
    ]
