# Generated by Django 5.2.4 on 2025-07-22 08:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_mediaattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaattachment',
            name='image_name',
        ),
        migrations.AddField(
            model_name='mediaattachment',
            name='caption',
            field=models.TextField(default='No caption'),
        ),
        migrations.AddField(
            model_name='mediaattachment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediaattachment',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediaattachment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mediaattachment',
            name='image',
            field=models.ImageField(upload_to='uploaded-images/'),
        ),
    ]
