# Generated by Django 5.2.8 on 2026-01-26 11:42
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_post_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="images",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="revision",
            field=models.IntegerField(default=1),
        ),
    ]
