# Generated by Django 5.2.4 on 2025-07-28 07:37

import storages.backends.gcloud
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_mediaattachment_image_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleBucketAttachment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(storage=storages.backends.gcloud.GoogleCloudStorage(), upload_to='uploaded-images')),
            ],
        ),
    ]
