# Generated by Django 5.2.10 on 2026-02-03 13:25
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_images_is_featured_post_revision"),
    ]

    operations = [
        migrations.AddField(
            model_name="images",
            name="attribution",
            field=models.CharField(
                blank=True, default="Jan Stankiewicz", max_length=255, null=True
            ),
        ),
    ]
