# Generated by Django 5.2.4 on 2025-07-28 07:39

import storages.backends.gcloud
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_googlebucketattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlebucketattachment',
            name='image',
            field=models.ImageField(storage=storages.backends.gcloud.GoogleCloudStorage(), upload_to='rewilding/images'),
        ),
        migrations.AlterField(
            model_name='mediaattachment',
            name='image',
            field=models.ImageField(storage=storages.backends.gcloud.GoogleCloudStorage(), upload_to='rewilding/images'),
        ),
    ]
