# Generated by Django 5.2.10 on 2026-02-20 06:33

import blog.models
import django.core.validators
import storages.backends.gcloud
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_videos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videos",
            name="video",
            field=models.FileField(
                storage=storages.backends.gcloud.GoogleCloudStorage(),
                upload_to=blog.models.get_image_filename,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["MOV", "avi", "mp4", "webm", "mkv"]
                    )
                ],
                verbose_name="Video",
            ),
        ),
    ]
