# Generated by Django 5.2.4 on 2025-08-02 07:16

import blog.models
import django.db.models.deletion
import storages.backends.gcloud
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=storages.backends.gcloud.GoogleCloudStorage(), upload_to=blog.models.get_image_filename, verbose_name='Image')),
                ('caption', models.TextField(default='No caption')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
        ),
    ]
