# Generated by Django 5.2.10 on 2026-02-28 12:29

import blog.models
import django.core.validators
import storages.backends.gcloud
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_alter_videos_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="images",
            name="image",
            field=models.ImageField(
                storage=storages.backends.gcloud.GoogleCloudStorage(),
                upload_to=blog.models.get_image_filename,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "gif"]
                    )
                ],
                verbose_name="Image",
            ),
        ),
    ]
