# Generated by Django 5.2.4 on 2025-08-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_gpscoordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
