# Generated by Django 5.2.8 on 2025-11-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial_squashed_0011_alter_images_caption"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediaattachment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="mediaattachment",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="post",
            name="date",
            field=models.DateField(),
        ),
    ]
