# Generated by Django 5.2.8 on 2025-12-14 07:13
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0012_alter_mediaattachment_created_at_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
