# Generated by Django 5.2.8 on 2025-12-14 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_delete_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MediaAttachment',
        ),
    ]
