# Generated by Django 5.2.8 on 2025-12-17 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_delete_mediaattachment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoogleBucketAttachment',
        ),
    ]
