# Generated by Django 5.2.8 on 2025-12-17 08:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_delete_googlebucketattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='uuid_field',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
