# Generated by Django 5.2.8 on 2025-12-17 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_post_uuid_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='uuid_field',
        ),
    ]
