"""
Django settings for blogged project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from google.oauth2 import service_account

from common.utils import get_secret


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_secret("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(os.environ.get("DEBUG", default=0))

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS").split(" ")
CSRF_TRUSTED_ORIGINS = ["http://localhost:1337"]  # TODO - update for production


# Application definition

INSTALLED_APPS = [
    'dal',
    'dal_select2',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # 'formset',  # https://django-formset.fly.dev/
    "django_flatpickr",
    "storages",
    "blog",
    "blogcontact",
    "impact_maps",
    # 'gdstorage',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "blogged.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "blogged.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


POSTGRES_PW = get_secret("POSTGRES_PASSWORD")


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("DB_NAME", "eco_blog"),
        "USER": os.environ.get("DB_USER"),
        "PASSWORD": POSTGRES_PW,
        "HOST": os.environ.get("DB_HOST", "localhost"),
        "PORT": os.environ.get("DB_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = "static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
# STATIC_ROOT = BASE_DIR.parent / "local-cdn" / "static"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# for email contact form (followed this blog post: https://learndjango.com/tutorials/django-email-contact-form-tutorial)
# need to follow the steps - "Production Email Service" to actually get the email to send
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
DEFAULT_FROM_EMAIL = "annonymous@gmail.com"
NOTIFY_EMAIL = "annonymous@gmail.com"  # TODO - use a secret for this?

# Google drive keys
GOOGLE_DRIVE_STORAGE_JSON_KEY_FILE = (
    "/home/jan/secrets/django-blog-data-9a52eb1b9db9.json"
)
GOOGLE_DRIVE_STORAGE_MEDIA_ROOT = (
    "blog/rewilding/images"  # <base google drive path for file uploads>' # OPTIONAL
)

# STORAGES = {
#     "default": {
#         "BACKEND": "storages.backends.gcloud.GoogleCloudStorage",
#         "OPTIONS": {
#           "GS_BUCKET_NAME": 'django-blog-data',
#           "GS_PROJECT_ID": 'django-blog-data',
#           "GS_CREDENTIALS": service_account.Credentials.from_service_account_file("/home/jan/secrets/django-blog-data-9a52eb1b9db9.json"),
#         },
#     },
#     'staticfiles': {
#         'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
#         'OPTIONS': {
#             'location': STATIC_ROOT,
#         },
#     }
# }


# google cloud - https://django-storages.readthedocs.io/en/latest/backends/gcloud.html
DEFAULT_FILE_STORAGE = "storages.backends.gcloud.GoogleCloudStorage"
GS_BUCKET_NAME = os.environ.get("GS_BUCKET_NAME")
GS_PROJECT_ID = os.environ.get("GS_PROJECT_ID")
GS_CREDENTIALS = service_account.Credentials.from_service_account_file(
    os.environ.get("GS_CREDENTIALS_PATH")
)

# For public access to images, set this to publicRead.
# GS_DEFAULT_ACL = 'publicRead' # Optional, but recommended for public images. Requires ACLs to be enabled on the bucket.
# For private images, you might want to use signed URLs.
GS_QUERYSTRING_AUTH = False  # Recommended for private images and when using signed URLs


LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"


# Check required envs exist
required_envs = ["PROJECT_DB_TAG"]

for env in required_envs:
    if not os.environ.get(env):
        raise ValueError(f"Missing required env variable: {env}")
