# Generated by Django 5.2.8 on 2026-01-19 14:11
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("blog", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("TA", "Talla & Gameshope"),
                            ("CA", "Carrifran"),
                            ("CO", "Corehead"),
                            ("DU", "Dundreggan"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to="blog.post",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TreeSpecies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("common_name", models.CharField(max_length=100)),
                ("genus", models.CharField(max_length=100)),
                ("specific_epithet", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ActivityTreePlantingSession",
            fields=[
                (
                    "activity_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="activities.activity",
                    ),
                ),
                ("notes", models.CharField(max_length=200, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("activities.activity",),
        ),
        migrations.CreateModel(
            name="ActivityVoleGuardRemoval",
            fields=[
                (
                    "activity_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="activities.activity",
                    ),
                ),
                ("area_covered", models.FloatField()),
                ("plastic_removed", models.FloatField(null=True)),
                ("trees_liberated", models.IntegerField(null=True)),
                ("gps_track", models.JSONField(null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("activities.activity",),
        ),
        migrations.CreateModel(
            name="TransportCar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("distance", models.FloatField()),
                ("carbon_offset", models.BooleanField()),
                ("passengers", models.IntegerField(default=0)),
                (
                    "powertrain",
                    models.CharField(
                        choices=[
                            ("E", "Electric"),
                            ("H", "Hybrid"),
                            ("G", "Gasoline"),
                            ("D", "Diesel"),
                        ],
                        default="E",
                        max_length=1,
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="activities.activity",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TransportPublic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("distance", models.FloatField()),
                ("carbon_offset", models.BooleanField()),
                (
                    "type",
                    models.CharField(
                        choices=[("B", "Bus"), ("T", "Train")],
                        default="B",
                        max_length=1,
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="activities.activity",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ActivityInvasiveSpeciesRemoval",
            fields=[
                (
                    "activity_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="activities.activity",
                    ),
                ),
                ("quantity_removed", models.FloatField()),
                ("gps_track", models.JSONField(null=True)),
                (
                    "species_removed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="activities.treespecies",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("activities.activity",),
        ),
        migrations.CreateModel(
            name="TreePlanting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("gps_data", models.JSONField()),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tree_plantings",
                        to="activities.treespecies",
                    ),
                ),
                (
                    "trees_planted",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tree_plantings",
                        to="activities.activitytreeplantingsession",
                    ),
                ),
            ],
        ),
    ]
