# Generated by Django 5.2.8 on 2026-01-22 08:04
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="treeplanting",
            name="planting_style",
            field=models.IntegerField(
                choices=[(0, "Plug"), (1, "Bare root")], default=0
            ),
        ),
    ]
