# Generated by Django 5.2.8 on 2026-01-22 09:26
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0002_treeplanting_planting_style"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treeplanting",
            name="gps_data",
            field=models.JSONField(null=True),
        ),
    ]
