# Generated by Django 5.2.8 on 2026-01-23 09:22
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0003_alter_treeplanting_gps_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transportcar",
            name="carbon_offset",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="transportpublic",
            name="carbon_offset",
            field=models.BooleanField(default=False),
        ),
    ]
