# Generated by Django 5.2.8 on 2026-01-23 09:46
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0004_alter_transportcar_carbon_offset_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityTraining",
            fields=[
                (
                    "activity_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="activities.activity",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("activities.activity",),
        ),
        migrations.CreateModel(
            name="ActivityWorkshop",
            fields=[
                (
                    "activity_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="activities.activity",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("activities.activity",),
        ),
    ]
