# Generated by Django 5.2.8 on 2026-01-26 11:42
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0006_activitysurveying"),
        ("blog", "0005_images_is_featured_post_revision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="post",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="activities",
                to="blog.post",
            ),
        ),
    ]
