# Generated by Django 5.2.8 on 2026-01-26 13:43
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0007_alter_activity_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="hours_spent",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
