# Generated by Django 5.2.8 on 2026-01-27 09:59
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0008_activity_hours_spent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="hours_spent",
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
