# Generated by Django 5.2.10 on 2026-02-17 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0009_alter_activity_hours_spent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="location",
            field=models.CharField(
                choices=[
                    ("TA", "Talla & Gameshope"),
                    ("CA", "Carrifran"),
                    ("CO", "Corehead"),
                    ("DU", "Dundreggan"),
                    ("PGC", "Peebles Golf Course"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="TransportWalking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("distance", models.FloatField()),
                ("carbon_offset", models.BooleanField(default=False)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="activities.activity",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
