# Generated by Django 5.2.10 on 2026-04-30 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0010_alter_activity_location_transportwalking"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityTreeGuardRemoval",
            fields=[
                (
                    "activity_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="activities.activity",
                    ),
                ),
                ("tubes_removed", models.IntegerField(null=True)),
                ("tube_weight_g", models.FloatField(default=90.0)),
                ("gps_track", models.JSONField(null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("activities.activity",),
        ),
    ]
