# Generated by Django 5.2.10 on 2026-05-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0011_activitytreeguardremoval"),
    ]

    operations = [
        migrations.AddField(
            model_name="treespecies",
            name="subspecies",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
